### ISSUE TITLE
config.py: 'settings' is not defined

### ISSUE THREAD

**Issue by xaero3** [skeetzo/onlysnarf#2]
First of all, this project is amazing. So happy to have stumbled upon this, thanks for making it.

Running the onlysnarf-config command, and I'm getting this error:
```
file ".../python3.6/site-packages/OnlySnarf/bin/config.py", line 112, in main
    if os.path.isfile(settings.CONFIG_PATH):
NameError: name 'settings' is not defined
```
Trying to trace down what 'settings' is referring to... Can only think that it may be trying to reference data that one of the settings.py getter funcs is handling? Not sure.

Thanks!

**Comment by skeetzo** [comment]
Sorry, there's not much of a use case for the onlysnarf-config script for developers so it's kinda halfassed. I've updated the script to do a simple file prep for getting up and running in the latest push. All it does / all you need to do is copy/paste the config.conf file to the appropriate location and fill it with any runtime arguments you'd like to change. Specifically the (Twitter) username and password. The process for creating the google_creds.txt is a bit more elaborate than the setup script can provide.
